
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CONST IDENT PAREN PROC VARS : PROC IDENT PAREN P PARENP : VAR P\n        | CONST P \n        | emptyempty : '
    
_lr_action_items = {'PROC':([0,],[2,]),'$end':([1,9,],[0,-1,]),'IDENT':([2,],[3,]),'PAREN':([3,4,5,6,7,8,10,11,],[4,-5,9,-5,-5,-4,-2,-3,]),'VAR':([4,6,7,],[6,6,6,]),'CONST':([4,6,7,],[7,7,7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'P':([4,6,7,],[5,10,11,]),'empty':([4,6,7,],[8,8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> PROC IDENT PAREN P PAREN','S',5,'p_S','ejercicio2TP7.py',24),
  ('P -> VAR P','P',2,'p_P','ejercicio2TP7.py',27),
  ('P -> CONST P','P',2,'p_P','ejercicio2TP7.py',28),
  ('P -> empty','P',1,'p_P','ejercicio2TP7.py',29),
  ('empty -> <empty>','empty',0,'p_empty','ejercicio2TP7.py',32),
]
