
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADDITION E F NUMBER PAREN PRODUCT TEE : EE ADDITION TT\n        | TTTT : TT PRODUCT FF\n        | FFFF : NUMBER\n        | PAREN EE PAREN'
    
_lr_action_items = {'NUMBER':([0,5,6,7,],[4,4,4,4,]),'PAREN':([0,2,3,4,5,6,7,8,9,10,11,],[5,-2,-4,-5,5,5,5,11,-1,-3,-6,]),'$end':([1,2,3,4,9,10,11,],[0,-2,-4,-5,-1,-3,-6,]),'ADDITION':([1,2,3,4,8,9,10,11,],[6,-2,-4,-5,6,-1,-3,-6,]),'PRODUCT':([2,3,4,9,10,11,],[7,-4,-5,7,-3,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'EE':([0,5,],[1,8,]),'TT':([0,5,6,],[2,2,9,]),'FF':([0,5,6,7,],[3,3,3,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> EE","S'",1,None,None,None),
  ('EE -> EE ADDITION TT','EE',3,'p_EE','ejercicio1TP7.py',26),
  ('EE -> TT','EE',1,'p_EE','ejercicio1TP7.py',27),
  ('TT -> TT PRODUCT FF','TT',3,'p_TT','ejercicio1TP7.py',30),
  ('TT -> FF','TT',1,'p_TT','ejercicio1TP7.py',31),
  ('FF -> NUMBER','FF',1,'p_FF','ejercicio1TP7.py',34),
  ('FF -> PAREN EE PAREN','FF',3,'p_FF','ejercicio1TP7.py',35),
]
